### PR TITLE
Attempts to build wheels across more architectures

### LINKED ISSUE #119: Unable to import module on M1 Mac
When I tried to run a very simple "run this Starlark file":
```
$ python3 test.py .vela.star
Traceback (most recent call last):
  File "/Users/colin/myprojects/python-poetry/test.py", line 3, in <module>
    from starlark_go import Starlark
  File "/Users/colin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/starlark_go/__init__.py", line 9, in <module>
    from starlark_go.starlark_go import (  # pyright: reportMissingModuleSource=false
ImportError: dlopen(/Users/colin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/starlark_go/starlark_go.cpython-39-darwin.so, 0x0002): tried: '/Users/colin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/starlark_go/starlark_go.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```
When I check the library file, I can see that it's compiled in x86_64 mode only:
```
$ file /Users/colin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/starlark_go/starlark_go.cpython-39-darwin.so
/Users/colin/.pyenv/versions/3.9.11/lib/python3.9/site-packages/starlark_go/starlark_go.cpython-39-darwin.so: Mach-O 64-bit dynamically linked shared library x86_64
```
If it was universal, I'd expect to see `Mach-O universal binary with 2 architectures`, as alluded by running `file` on every shared object I've got installed in every Python version I've got installed:

```
$ cd ~/.pyenv/versions
$ fd '\.so' . --exec file | cut -d : -f 2 | sort | uniq -c
   2 	Mach-O 64-bit bundle arm64
   2 	Mach-O 64-bit bundle x86_64
1189  Mach-O 64-bit bundle arm64
   2  Mach-O 64-bit bundle x86_64
   1  Mach-O 64-bit dynamically linked shared library x86_64
   2  Mach-O universal binary with 2 architectures
```

Any other `Mach-O 64-bit dynamically linked shared library x86_64`?

```
$ fd '\.so' . --exec file | rg 'Mach-O 64-bit dynamically linked shared library x86_64'
./3.9.11/lib/python3.9/site-packages/starlark_go/starlark_go.cpython-39-darwin.so: Mach-O 64-bit dynamically linked shared library x86_64
```

No, just `starlark_go`.

Only others I've got installed shipping universal are [MarkupSafe](https://pypi.org/project/MarkupSafe/#files) and [uvloop](https://pypi.org/project/uvloop/#files):

```
$ fd '\.so' . --exec file | rg 'Mach-O universal binary with 2 architectures'
./3.10.2/envs/spiderbot/lib/python3.10/site-packages/uvloop/loop.cpython-310-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64Mach-O 64-bit bundle x86_64] [arm64]
./3.10.2/envs/spiderbot/lib/python3.10/site-packages/markupsafe/_speedups.cpython-310-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64Mach-O 64-bit bundle arm64]
```

The universal wheel for version 0.1.1 was installed:
```
$ pip install starlark-go
Looking in indexes: <internal repo URLs redacted>
Collecting starlark-go
  Downloading https://binrepo.mycompany.com/artifactory/api/pypi/pypi-remote/packages/packages/35/1d/7a3104a0038e5a77b20faec9cd2b110053304f8706369f6aa3db57ee0d11/starlark_go-0.1.1-cp39-cp39-macosx_10_9_universal2.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 2.1 MB/s eta 0:00:00
Installing collected packages: starlark-go
Successfully installed starlark-go-0.1.1
```

## My test runner

I'm not sure is even correct because of the import error:

```python
import sys

from starlark_go import Starlark

s = Starlark()

with open(sys.argv[1], 'r') as input_file:
    s.exec(input_file.read())

print(s.eval("main([])"))
```

## Versions:

```
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
$ uname -a
Darwin mycomputer 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
$ python --version
Python 3.9.11
```

## Possible remedy

It looks like [uvloop is using the ~same tool](https://github.com/MagicStack/uvloop/blob/afb326897c26f01b864f65f016a7f3f80d9db8ad/.github/workflows/release.yml#L72-L87) starlark-go is using to build, so maybe it can be adapted.

### PR DESCRIPTION
**Pull request by colindean**
Uses uvloop's configuration for inspiration/nearly direct copying.

https://github.com/MagicStack/uvloop/blob/afb326897c26f01b864f65f016a7f3f80d9db8ad/.github/workflows/release.yml#L72-L87

Fixes #119

### CODE REVIEW

**Comment by colindean** [comment]
N.b. this change is an (educated) shot in the dark.

**Comment by colindean** [comment]
It looks like the wheel building succeeded and what failed is that I don't have a token setup to test upload to pypi.

**Comment by jordemort** [comment]
I'll try and figure out how to run it with the token, I want to see how it looks on TestPyPI with the additional architectures before I merge.

**Comment by colindean** [comment]
Any change you'd take a look at this in the next few days?

**Comment by jordemort** [comment]
Thanks for the contribution!

I made a couple of tweaks:

- Actions was whining that ${{runner.os}} was a syntax error, so I just removed it
- Instead of building x86_64 for all the macOS versions and also universal2 for > 3.7, I switched > 3.7 to be universal2-only

Waiting for one more cycle of CI and then I'll merge. I've tagged this PR as a patch version bump so fresh wheels should be available on PyPI shortly thereafter.

**Comment by jordemort** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/caketop/python-starlark-go/actions/runs/3907857462) **New version**:[v0.1.2](https://github.com/caketop/python-starlark-go/releases/tag/v0.1.2) **Changes**:[v0.1.1...v0.1.2](https://github.com/caketop/python-starlark-go/compare/v0.1.1...v0.1.2)

**Comment by jordemort** [comment]
https://github.com/caketop/python-starlark-go/releases/tag/v0.1.2 is now available here and on PyPI.

It looks like we inadvertently dropped i686 support here; I'm going to wait and see if anyone complains about that before I worry about putting it back.

I put a release announcement on my blog: https://jordemort.dev/blog/python-starlark-go-0.1.2/

**Comment by colindean** [comment]
Thank you for merging and for the recognition!

**Pull request merged**
